base_url: "https://vas.mobifone.vn"        # chỉnh theo domain thực tế của bạn
login_url: "https://vas.mobifone.vn/msocial/crud.jsp?crud_type=sharing_partner/index.html&menu_id=145"  # hoặc URL trang login bạn đang mở
employee_search_url: "https://vas.mobifone.vn/msocial/crud.jsp?crud_type=sharing_partner/index.html&menu_id=145"
selectors:
  username_input: "input#username[name='username']"
  password_input: "input#password[name='password']"
  # nút Đăng nhập (loại button, gọi JS submitDetailsForm())
  login_submit: "button.btn.btn-success.btn-block.btn-flat"

  # các selector bên dưới để trống/tạm; sẽ cấu hình sau khi có trang tìm nhân viên
  search_input: "input[name='employeeId']"
  search_submit: "button[data-test='search']"
  employee_row: "tr[data-employee-row]"
  edit_button: "button[data-test='edit']"
  pos_input: "input[name='posId']"
  save_button: "button[type='submit']"

timeouts:
  default: 15000
  navigation: 20000

retries: 2
retry_backoff_seconds: 2